name: Run Docker Compose

on:
  push:
    branches:
      - main

env: 
  dockername: flask_tdc

jobs:
  docker:
    timeout-minutes: 1
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: build_container
      run: docker build -t ${dockername} ./flask_app

    - name: tag_it
      run: docker tag ${dockername} ${{ secrets.DOCKER_USERNAME }}/${dockername}

    - name: testps
      run: docker images

    - name: Login_DockerHub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: bush_it
      run: docker push ${{ secrets.DOCKER_USERNAME }}/${dockername}

    - name: clean_up
      if: always()
      run: docker rmi ${dockername}:latest ${{ secrets.DOCKER_USERNAME }}/${dockername}


